name: Deploy to RPIZelda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, rpizelda]

    defaults:
      run:
        working-directory: ${{ github.workspace }}   # use the repo that checkout just created

    steps:
      - uses: actions/checkout@v4          # default path == $GITHUB_WORKSPACE

      # (optional) log in to ghcr if you still pull any images
      # - name: ghcr login ...
      #   ...

      - name: Stop, build, recreate
        run: |
          docker compose down --remove-orphans || true
          docker compose pull --quiet || true          # keep if you still pull any images
          docker compose up -d --build --force-recreate --pull always
